group: "PPO"
job_type: "Relative-Actions"
name: "0"

training:
  env: "3dof-hit"
  env_args:
    action_type: "relative"
    jerk_penalty: False
    positive_reward_coef: 10
  num_envs: 60

comment: "!!!n_steps is per parallel environment!!!"
hyperparameters:
  n_steps: 250
  batch_size: 256
  learning_rate: 5.e-5

wandb:
  entity: "thifhi"
  project: "3dof-hit"
  mode: "online"

slurm:
  home: "/home/kit/stud/upgmi"
  partition: "single"
  n: 1
  c: 40
  t: 1800

local_testing:
  path: "logs/linear-constraints_30kstep_abs"
  env: "3dof-hit"
  env_args:
    action_type: "relative"
    jerk_penalty: True
