group: "RnnPPO"
job_type: "7dof_defend"
name: "test-recurrent-3"

model_type: "recurrent"

training:
  env: "7dof-defend"
  env_args:
    noise: True
    horizon: 300
    last_joint: True
  num_envs: 12

comment: "!!!n_steps is per parallel environment!!!"
hyperparameters:
  n_steps: 2048
  batch_size: 2048
  learning_rate: 5.e-5
  gamma: 1
  n_epochs: 10
  # policy_kwargs:
  #   ortho_init: False

wandb:
  entity: "omeryagmurlu"
  project: "7dof-ppo-defend"
  mode: "online"

slurm:
  home: "/home/kit/stud/uqtlv"
  partition: "single"
  n: 1
  c: 40
  t: 1800

local_testing:
  model_type: "recurrent"
  path: "logs/RnnPPO/7dof_defend/test-recurrent-3"
  env: "7dof-defend"
  env_args:
    noise: True
    horizon: 300
    last_joint: True