group: "FILL"
name: "FILL"

training:
  env: "3dof-hit-interpolate"
  num_envs: 60

comment: "!!!n_steps is per parallel environment!!!"
hyperparameters:
  n_steps: 1000
  batch_size: 256
  learning_rate: 3.e-4

wandb:
  entity: "thifhi"
  project: "FILL"
  mode: "disabled"

slurm:
  home: "/home/kit/stud/upgmi"
  partition: "single"
  n: 1
  c: 40
  t: 1200
