group: "PPO"
job_type: "7dof_hit_2409"
name: "test-23"

training:
  env: "7dof-hit"
  env_args:
    noise: True
    horizon: 500
  num_envs: 12

comment: "!!!n_steps is per parallel environment!!!"
hyperparameters:
  n_steps: 256
  batch_size: 256
  learning_rate: 3.e-4
  gamma: 1
  n_epochs: 10
  # gae_lambda: 0.95
  # vf_coef: 0.25
  # ent_coef: 0.005
  # policy_kwargs:
    # ortho_init: False
    # net_arch:
    #   pi: [128, 128]
    #   vf: [128, 128]

wandb:
  entity: "marcus-fiedler"
  project: "bounce-reward"
  mode: "online"

slurm:
  home: "/home/kit/stud/ucsqq"
  partition: "single"
  n: 1
  c: 40
  t: 1800

local_testing:
  # path: "logs/PPO/7dof_prepare/test-183"
  # env: "7dof-ik"
  # path: "logs/PPO/7dof_prepare/test-228"
  # env: "7dof-hit-ik"
  # path: "logs/downloaded/7dof_hit/test-1"
  # env: "7dof-hit"
  # path: "logs/PPO/7dof_prepare/test-238"
  # env: "7dof-hit-ik"
  path: "logs/PPO/7dof_hit_2409/test-19"
  env: "7dof-ik"
  env_args:
    noise: True
    horizon: 500